# System packages to install via dnf
packages = [
    "NetworkManager-adsl",
    "NetworkManager-bluetooth",
    "NetworkManager-config-connectivity-fedora",
    "NetworkManager-openconnect-gnome",
    "NetworkManager-openvpn-gnome",
    "NetworkManager-ppp",
    "NetworkManager-pptp-gnome",
    "NetworkManager-ssh-gnome",
    "NetworkManager-vpnc-gnome",
    "PackageKit-command-not-found",
    "PackageKit-gstreamer-plugin",
    "PackageKit-gtk3-module",
    "Sunshine",
    "aajohan-comfortaa-fonts",
    "abrt-cli",
    "abrt-desktop",
    "adobe-source-code-pro-fonts",
    "alsa-sof-firmware",
    "alsa-utils",
    "anaconda-install-env-deps",
    "anaconda-live",
    "anaconda-webui",
    "ark",
    "at",
    "audit",
    "b43-fwcutter",
    "b43-openfwwf",
    "baobab",
    "bash-color-prompt",
    "bc",
    "bind-utils",
    "bluez-cups",
    "brltty",
    "btop",
    "buildah",
    "cargo",
    "cifs-utils",
    "compsize",
    "cosmic-edit",
    "cosmic-player",
    "cosmic-store",
    "crontabs",
    "cyrus-sasl-plain",
    "dconf-editor",
    "default-editor",
    "default-fonts-cjk-mono",
    "default-fonts-cjk-sans",
    "default-fonts-cjk-serif",
    "default-fonts-core-emoji",
    "default-fonts-core-math",
    "default-fonts-core-mono",
    "default-fonts-core-serif",
    "default-fonts-other-mono",
    "default-fonts-other-sans",
    "default-fonts-other-serif",
    "deltarpm",
    "desktop-backgrounds-gnome",
    "dhcp-client",
    "dnf5",
    "dnf5-plugins",
    "dos2unix",
    "dracut-config-rescue",
    "dracut-live",
    "ed",
    "efibootmgr",
    "evince",
    "fedora-bookmarks",
    "fedora-chromium-config",
    "fedora-flathub-remote",
    "fedora-workstation-backgrounds",
    "fedora-workstation-repositories",
    "firewalld",
    "fpaste",
    "fros-gnome",
    "gamemode",
    "git",
    "gnome-backgrounds",
    "gnome-boxes",
    "gnome-browser-connector",
    "gnome-calculator",
    "gnome-calendar",
    "gnome-characters",
    "gnome-classic-session",
    "gnome-clocks",
    "gnome-connections",
    "gnome-contacts",
    "gnome-disk-utility",
    "gnome-epub-thumbnailer",
    "gnome-extensions-app",
    "gnome-font-viewer",
    "gnome-initial-setup",
    "gnome-logs",
    "gnome-maps",
    "gnome-shell-extension-background-logo",
    "gnome-software",
    "gnome-system-monitor",
    "gnome-text-editor",
    "gnome-tweaks",
    "gnome-user-docs",
    "gnome-user-share",
    "gnome-weather",
    "grub2-efi-ia32-cdboot",
    "grub2-efi-x64-cdboot",
    "grub2-efi-x64-modules",
    "grub2-pc",
    "grub2-tools-efi",
    "grub2-tools-extra",
    "gstreamer1-plugin-dav1d",
    "gstreamer1-plugin-libav",
    "gutenprint-cups",
    "gvfs-afp",
    "gvfs-archive",
    "gvfs-gphoto2",
    "gvfs-mtp",
    "gvfs-smb",
    "hplip",
    "htop",
    "hyperv-daemons",
    "ibus-anthy",
    "ibus-chewing",
    "ibus-gtk4",
    "ibus-hangul",
    "ibus-libpinyin",
    "ibus-m17n",
    "ibus-typing-booster",
    "initial-setup-gui",
    "intel-vsc-firmware",
    "iptstate",
    "irqbalance",
    "iwlegacy-firmware",
    "iwlwifi-dvm-firmware",
    "iwlwifi-mvm-firmware",
    "kernel",
    "kernel-modules-extra",
    "libertas-firmware",
    "libreoffice-emailmerge",
    "libva-intel-media-driver",
    "livesys-scripts",
    "loupe",
    "lrzsz",
    "mactel-boot",
    "man-db",
    "man-pages",
    "mcelog",
    "mediawriter",
    "microcode_ctl",
    "mpage",
    "mtr",
    "neovim",
    "net-tools",
    "nheko",
    "okular",
    "open-vm-tools-desktop",
    "opensc",
    "openssh-server",
    "orca",
    "pam_afs_session",
    "paps",
    "passwdqc",
    "perl-Image-ExifTool",
    "pinfo",
    "pipewire-alsa",
    "pipewire-utils",
    "pipx",
    "plocate",
    "plymouth-system-theme",
    "podman-compose",
    "podman-docker",
    "prefixdevname",
    "psacct",
    "ptyxis",
    "qadwaitadecorations-qt5",
    "qemu-guest-agent",
    "qt5-qtxmlpatterns",
    "rhythmbox",
    "rocm-clinfo",
    "rocm-dev",
    "rocm-opencl",
    "rocm-runtime",
    "rocm-smi",
    "rocminfo",
    "rootfiles",
    "rpmfusion-free-release",
    "rsyslog",
    "samba-client",
    "shim-ia32",
    "shim-x64",
    "simple-scan",
    "snapshot",
    "sos",
    "spice-vdagent",
    "spice-webdavd",
    "sssd-kcm",
    "sssd-proxy",
    "sudo",
    "sushi",
    "symlinks",
    "system-config-printer-udev",
    "systemd-oomd-defaults",
    "tcpdump",
    "thermald",
    "thunderbird",
    "time",
    "toolbox",
    "totem",
    "traceroute",
    "tree",
    "unoconv",
    "uresourced",
    "usb_modeswitch",
    "vim-enhanced",
    "vim-minimal",
    "virt-manager",
    "virt-viewer",
    "virtualbox-guest-additions",
    "wget2-wget",
    "whois",
    "wireguard-tools",
    "words",
    "yelp",
    "zip",
    "zram-generator-defaults",
]
